-- Nexa — devices, and the pairing that puts one on an account.
--
-- The account already exists: `companion_bindings` says which companion a
-- verified `user_id` may act as. What has never existed is the *device* — the
-- particular headset in the room — and the ceremony by which an authenticated
-- phone vouches for one.
--
-- ## The property this schema exists to enforce
--
-- A pairing code that is photographed, decoded and replayed by somebody else's
-- headset must be worthless. Three columns carry that weight:
--
--   * `pairing_sessions.code_hash` — the code is never stored, only its digest,
--     so a database disclosure yields nothing redeemable.
--   * `pairing_sessions.headset_public_key` — **not null**. A session that is
--     not bound to one specific headset is not representable, so there is no
--     code path in which a code alone is sufficient. This is the constraint
--     that makes the security property structural rather than a matter of
--     remembering to check.
--   * the partial unique index on `(code_hash) where status = 'pending'`, which
--     is what lets redemption be a single atomic conditional UPDATE rather than
--     a read followed by a write two headsets could both win.
--
-- ## Conventions followed from 0001–0004
--
-- Ids are `text` and generated by the application, as in 0001 — they are the
-- branded id types from `@nexa/shared`, and a database-generated uuid would be
-- a second identity for the same thing. Timestamps are `timestamptz`. Live
-- subsets are expressed as partial indexes, exactly as
-- `companion_bindings_one_owner_idx` and `insights_owner_live_key_idx` are.
-- Row level security is enabled with no policies.
--
-- ## Two deliberate departures, both narrow
--
-- **Foreign keys between these tables.** 0004 declines a foreign key into
-- `auth.users`, and gives its reason precisely: `auth` is Supabase's schema and
-- a hard reference would couple the migration to a platform detail. That
-- argument is about crossing into Supabase's territory. It says nothing about
-- references among Nexa's own tables, where an orphaned pairing session or a
-- token belonging to no device is simply a bug waiting to be read as data.
-- Deletion is intentionally left as NO ACTION: devices are revoked, not
-- deleted, and a foreign key that quietly cascaded would erase the audit trail
-- of a revocation.
--
-- **Check constraints.** 0001–0004 use none. These do, on the two columns whose
-- vocabulary is load-bearing — `kind` and `status`. Both are branched on by
-- security-relevant code, and a typo that silently produced an unreachable
-- status is exactly the failure a check constraint is for. The cost is that
-- adding a status becomes a migration, which for a state machine that governs
-- credential redemption is the correct cost.
--
-- `user_id` remains `text`, holding the Supabase `auth.uid()` taken from a
-- verified token's `sub`. There is still no `users` table and still no foreign
-- key into `auth`.

-- ── devices ─────────────────────────────────────────────────────────────────
--
-- One row per physical device on an account. A phone earns its row by being
-- signed in; a headset earns its row only by completing a pairing.
create table if not exists devices (
  id                  text        primary key,
  user_id             text        not null,

  -- 'phone' or 'headset'. Deliberately NOT the `DEVICE_KINDS` vocabulary in
  -- `@nexa/models` — that one is microphone/speaker/camera/display/headset/
  -- controller, which describes hardware a *body* reports and is a different
  -- concept that happens to share a word.
  kind                text        not null,
  label               text,

  -- The headset's cryptographic identity: X.509 SubjectPublicKeyInfo DER for
  -- an EC P-256 key, as Android's `publicKey.getEncoded()` returns it.
  --
  -- Null for a phone, which proves itself with its Supabase session and needs
  -- no key of its own. Never null for a headset — see the check below — because
  -- a headset with no key is a headset that cannot prove it is itself.
  --
  -- The matching private key is generated inside the headset's keystore and
  -- never leaves it. It is not in this table, not in the pairing code, and
  -- never sent anywhere.
  public_key          bytea,
  -- base64url SHA-256 of `public_key`. The fingerprint shown to the user, and
  -- the lookup handle. Derived, stored, and never authoritative on its own.
  public_key_id       text,
  -- 'software' | 'tee' | 'strongbox' | 'unknown', as the device reported it.
  -- Self-reported and therefore evidence of nothing until key attestation
  -- exists; kept so a software-backed key can be refused outside development,
  -- and so a silent fallback is visible rather than invisible.
  key_security_level  text,

  registered_at       timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  last_seen_at        timestamptz,

  -- Set when the user forgets this device. A revocation, not a delete: the row
  -- stays so the key that was removed remains readable, and so a revoked key
  -- presenting itself again can be recognised rather than silently re-trusted.
  revoked_at          timestamptz,

  constraint devices_kind_check
    check (kind in ('phone', 'headset')),

  constraint devices_headset_has_key_check
    check (kind <> 'headset' or (public_key is not null and public_key_id is not null)),

  -- A loose sanity bound on a P-256 SPKI, which is 91 bytes. Wide enough to
  -- survive a curve change, tight enough to catch the classic mistake of
  -- writing base64 text into a bytea column.
  constraint devices_public_key_shape_check
    check (public_key is null or octet_length(public_key) between 64 and 200),

  constraint devices_key_security_level_check
    check (key_security_level is null
           or key_security_level in ('software', 'tee', 'strongbox', 'unknown'))
);

-- "List the devices on this account", which is every read the Devices screen
-- performs. Partial, because a forgotten device is not one of them.
create index if not exists devices_user_idx
  on devices (user_id)
  where revoked_at is null;

-- One live device per key. Partial rather than total, for the same reason
-- `companion_bindings_one_owner_idx` is: a revoked device must be able to pair
-- again later, and a total unique index would make forgetting a headset
-- permanent. Two *live* devices sharing a key would mean two things able to
-- prove they are the same headset, which must never happen.
create unique index if not exists devices_live_key_idx
  on devices (public_key_id)
  where revoked_at is null and public_key_id is not null;

-- ── pairing sessions ────────────────────────────────────────────────────────
--
-- One session is one attempt, carrying exactly one credential. There is no
-- rotating family of codes: a code that expires does not get replaced within
-- its session, because a new code on screen genuinely is a new attempt, and
-- modelling it as one keeps the redemption predicate a single row lookup.
create table if not exists pairing_sessions (
  id                      text        primary key,
  user_id                 text        not null,

  -- Which authenticated device vouched. The account on this row came from that
  -- phone's verified token, never from a request body.
  phone_device_id         text        not null references devices (id),

  -- SHA-256 of the single-use secret the phone displays. The secret itself is
  -- returned to the phone once, at creation, and is not stored, not logged and
  -- not recoverable. A code that could be read back twice would not be single
  -- use, whatever the status column said.
  code_hash               text        not null,

  -- The headset this session is bound to, captured over the local channel
  -- before the code was ever shown. NOT NULL is the point: an unbound session
  -- cannot be written, so no code path can treat a code alone as sufficient.
  --
  -- Redemption verifies the proof against THIS key. A public key arriving in a
  -- redeem request is a claim and must never be substituted for this column.
  headset_public_key      bytea       not null,
  headset_public_key_id   text        not null,
  headset_key_security_level text,

  -- Reserved. Whatever the local channel learned about the headset beyond its
  -- key — an advertised name, worth showing in a picker. Nullable and carries
  -- no authority; the binding above is what identifies the headset.
  headset_hint            text,

  status                  text        not null default 'pending',

  -- Bad proofs against this session. A ceiling exists so a session cannot be
  -- hammered, but burning the session on the first bad signature would let
  -- anyone who photographed the screen cancel a stranger's setup.
  attempt_count           integer     not null default 0,

  created_at              timestamptz not null default now(),
  expires_at              timestamptz not null,
  redeemed_at             timestamptz,
  cancelled_at            timestamptz,
  redeemed_by_device_id   text        references devices (id),

  constraint pairing_sessions_status_check
    check (status in ('pending', 'redeemed', 'expired', 'cancelled', 'failed')),

  constraint pairing_sessions_public_key_shape_check
    check (octet_length(headset_public_key) between 64 and 200),

  -- A session may not claim to be redeemed without recording when, and by
  -- which device. Without this the audit trail is optional, and an optional
  -- audit trail is the one that turns out to be missing.
  constraint pairing_sessions_redeemed_check
    check (status <> 'redeemed'
           or (redeemed_at is not null and redeemed_by_device_id is not null)),

  constraint pairing_sessions_cancelled_check
    check (status <> 'cancelled' or cancelled_at is not null)
);

-- The index redemption turns on.
--
--   update pairing_sessions
--      set status = 'redeemed', redeemed_at = now(), redeemed_by_device_id = $2
--    where code_hash = $1 and status = 'pending' and expires_at > now()
--   returning ...
--
-- Unique over pending rows only, so that lookup can match at most one session
-- and two concurrent redemptions of the same code resolve to exactly one
-- winner in the database rather than in application code. Partial for the same
-- reason `insights_owner_live_key_idx` is: redeemed and expired rows stay
-- readable as history and must not compete for the constraint.
create unique index if not exists pairing_sessions_live_code_idx
  on pairing_sessions (code_hash)
  where status = 'pending';

-- "What has this account been doing", for the phone's poll and for support.
create index if not exists pairing_sessions_user_idx
  on pairing_sessions (user_id, created_at desc);

-- For sweeping sessions that were never redeemed. The sweep is tidiness only —
-- expiry is enforced by `expires_at > now()` inside the redemption predicate,
-- so a sweeper that never runs cannot make a stale code redeemable.
create index if not exists pairing_sessions_pending_expiry_idx
  on pairing_sessions (expires_at)
  where status = 'pending';

-- ── device tokens ───────────────────────────────────────────────────────────
--
-- What a paired headset holds afterwards. Only the refresh credential lives
-- here, hashed. The short-lived access token is a signed JWT verified in
-- process and is deliberately not stored at all — writing it down would create
-- a second copy of a secret that the system is designed never to need.
create table if not exists device_tokens (
  id            text        primary key,
  device_id     text        not null references devices (id),

  -- Denormalised from `devices` so the refresh path is a single row read on the
  -- hot path, matching how `companion_bindings` is read before any work starts.
  user_id       text        not null,

  -- SHA-256 of the refresh token, for the same reason `code_hash` is a hash.
  token_hash    text        not null,

  issued_at     timestamptz not null default now(),
  expires_at    timestamptz not null,
  last_used_at  timestamptz,

  -- What makes "Forget this device" actually end the headset's access rather
  -- than merely hide it from a list.
  revoked_at    timestamptz,

  -- Rotation chain. A refresh token presented after it was replaced means two
  -- parties hold it, which is how theft is detected rather than assumed absent.
  replaced_by   text        references device_tokens (id)
);

-- A refresh token hash identifies exactly one row. Total rather than partial:
-- a rotated or revoked hash must never be reissued to a different row, because
-- reuse detection depends on the old row still being findable.
create unique index if not exists device_tokens_hash_idx
  on device_tokens (token_hash);

-- "Revoke everything this device holds", and the live-token read on refresh.
create index if not exists device_tokens_device_idx
  on device_tokens (device_id)
  where revoked_at is null;

-- ── row level security ──────────────────────────────────────────────────────
--
-- Enabled with no policies, exactly as 0002 and 0004 do it. RLS with no policy
-- denies every role it applies to, and the backend connects as the tables'
-- owner, which bypasses it. There is nothing here a client should ever read
-- directly, and two columns make that emphatic: `pairing_sessions.code_hash`
-- and `device_tokens.token_hash` must not be reachable through PostgREST by
-- anyone holding the project's publishable key.
--
-- When the backend stops being the owner — see the note in 0002 — these three
-- tables need policies alongside the others.
alter table public.devices           enable row level security;
alter table public.pairing_sessions  enable row level security;
alter table public.device_tokens     enable row level security;
