-- Nexa — a headset publishes its public key before anyone can vouch for it.
--
-- NX2 step 2. The headset generates a key inside its own keystore, enrols the
-- *public* half here, and receives a short-lived random handle. The local
-- channel — Bluetooth, the local network, or a person reading a screen — then
-- carries only that handle. The key itself never travels through it.
--
-- ## Why the handle and not the key
--
-- A local channel can be substituted or eavesdropped, and a public key needs
-- integrity rather than secrecy. Moving the key over that channel would make
-- the channel responsible for a trust decision it cannot make. Moving a handle
-- instead means the channel carries a *pointer*, the backend resolves it, and
-- what the phone binds is the key this table already holds.
--
-- ## What an enrolment is not
--
-- It is a publication, not an authentication. Holding a handle grants no
-- account access, no device credential, no token, no companion binding and no
-- pairing. It names a public key and nothing else, which is what makes it safe
-- for the enrolling endpoint to be unauthenticated — the headset has no
-- credential yet, so requiring one would make the flow impossible.
--
-- The handle is 256 bits of CSPRNG output, stored only as its SHA-256. It is
-- deliberately not shortened for human typing: if a readable code is ever
-- wanted, that belongs in a display layer above this, not in the value the
-- protocol turns on.
--
-- Conventions are 0005's throughout: `text` ids generated by the application,
-- `timestamptz`, hashes rather than plaintext, `bytea` SPKI with the same
-- sanity bound, the same `key_security_level` vocabulary, named check
-- constraints, partial indexes over the live subset, and row level security
-- enabled with no policies. No foreign key into Supabase's `auth` schema and
-- no users table. Migrations 0001–0005 are untouched.

create table if not exists device_enrolments (
  id                      text        primary key,

  -- SHA-256 of the handle, base64url. The handle itself is returned to the
  -- headset exactly once and is not stored, not logged and not recoverable —
  -- the same rule `pairing_sessions.code_hash` follows, for the same reason.
  handle_hash             text        not null,

  -- X.509 SubjectPublicKeyInfo DER for an EC P-256 key, as Android's
  -- `publicKey.getEncoded()` returns it. NOT NULL: an enrolment that names no
  -- key is not an enrolment, and the whole point of this table is that the key
  -- exists before anything references it.
  public_key              bytea       not null,

  -- base64url SHA-256 of `public_key`. The fingerprint a user compares across
  -- two screens, and the lookup handle. Derived, never authoritative alone.
  public_key_id           text        not null,

  -- As the device reported it. Self-reported, so evidence of nothing until key
  -- attestation exists; kept so a software-backed key can be refused outside
  -- development, and so a silent fallback to software is visible.
  key_security_level      text,

  created_at              timestamptz not null default now(),
  expires_at              timestamptz not null,

  -- Consumed, never deleted. The row is the audit record of which key a
  -- pairing session was bound to, and when — deleting it would erase the only
  -- evidence of how a headset came to be trusted.
  consumed_at             timestamptz,
  consumed_by_session_id  text        references pairing_sessions (id),

  -- The same loose bound 0005 puts on a P-256 SPKI (91 bytes). Wide enough to
  -- survive a curve change, tight enough to catch base64 text written into a
  -- bytea column.
  constraint device_enrolments_public_key_shape_check
    check (octet_length(public_key) between 64 and 200),

  constraint device_enrolments_key_security_level_check
    check (key_security_level is null
           or key_security_level in ('software', 'tee', 'strongbox', 'unknown')),

  -- An enrolment may not name the session that consumed it without recording
  -- when. Without this the audit trail is optional, and an optional audit
  -- trail is the one that turns out to be missing.
  constraint device_enrolments_consumed_check
    check (consumed_by_session_id is null or consumed_at is not null)
);

-- One live enrolment per handle, so resolving a handle matches at most one row
-- and two concurrent consumptions resolve to exactly one winner in the
-- database rather than in application code.
--
-- Partial over the unconsumed set, mirroring `pairing_sessions_live_code_idx`:
-- consumed rows stay readable as history and must not compete for the
-- constraint. Expiry is deliberately not in the predicate — `now()` is not
-- immutable and cannot be indexed — so it is enforced in the resolve query,
-- exactly as `expires_at` is for redemption.
create unique index if not exists device_enrolments_live_handle_idx
  on device_enrolments (handle_hash)
  where consumed_at is null;

-- For sweeping enrolments nobody ever used. Tidiness only: expiry is enforced
-- in the query predicate, so a sweeper that never runs cannot make a stale
-- handle resolvable.
create index if not exists device_enrolments_live_expiry_idx
  on device_enrolments (expires_at)
  where consumed_at is null;

-- Locked to the backend exactly as 0002, 0004 and 0005 are. Enabled with no
-- policies: RLS with no policy denies every role it applies to, and the
-- backend connects as the owner. `handle_hash` in particular must not be
-- reachable through PostgREST by anyone holding the publishable key.
alter table public.device_enrolments enable row level security;
